site_name: Mohammed Besar Blog
site_author: Mohammed Besar
site_description: Linux and Open Source Software.
copyright: Copyright &copy; 2022 Mohammed Besar

repo_url: https://github.com/mmBesar/Tutorials

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Tutorials:
      - Tutorials/appimages.md
      - Tutorials/Best-Arabic-Font-in-Linux.md
      - Tutorials/Debian-Post-Install.md
      - Tutorials/elementaryOS6-PostInstall.md
      - Tutorials/Fedora-Post.md
      - Tutorials/gnome-keybindings.md
      - Tutorials/macOS-theme-for-Ubuntu.md
      - Tutorials/PopShell-Install.md
      - Tutorials/tesseract.md
      - Tutorials/Ubuntu-Post-Install.md
      - Tutorials/VirtManager.md
      - Tutorials/VirtManager-Share.md
      - Tutorials/Waydroid.md
      - Tutorials/Xfce-Customized-Debian-11.md
      - Tutorials/ZSH.md
      - Tutorials/Ubuntu-Update.md
      - Tutorials/VirtManager-Win11.md
      - Tutorials/VirtManager-Win-Share.md
  - About: about.md

theme:
  custom_dir: overrides
  name: material
  logo: /assets/logo-white.png
  favicon: /assets/logo.png
  # font: false
  # icon:
  #   logo: material/home
  # Light and Dark Theme Toggle

  # palette:
  #   - media: "(prefers-color-scheme: light)"
  #     scheme: default
  #     toggle:
  #       icon: material/weather-night
  #       name: Switch to dark mode
  #   - media: "(prefers-color-scheme: dark)"
  #     scheme: slate
  #     primary: red
  #     accent: pink
  #     toggle:
  #       icon: material/weather-sunny
  #       name: Switch to light mode

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.indexes
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.sections
    # - toc.integrate

plugins:
  - mkdocs-video
  - search:
      lang:
        - en
        - ar

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.online/@mbesar
      name: Mastodon
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mmbesar
      name: Twitter
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/mmbesar
      name: Instagram
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/Mohammed.Besar.Page
      name: Facebook Page
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/mmbesar
      name: YouTube Channel
    # - icon: fontawesome/solid/paper-plane
    #   link: mailto:mbesar@proton.me
    #   name: Send Me an email
      
  blog:
    dir: Tutorials
    author: Mohammed Besar
    author_image: /assets/author.jpg
    words_read_per_minute: 300
    list_length: 5
    extended_preview: true

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - def_list
  - footnotes
  - tables
  - toc:
      title: On this page
      # permalink: true
      permalink: ⚓︎
      baselevel: 3
      toc_depth: 6
      separator: "_"
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      # slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view

  # blog
  - meta

